export { default as DashboardPage } from './Dashboard'
export { default as ProfilePage } from './Profile'
export { default as EditProfilePage } from './EditProfile'
export { default as PageNotFound } from './404'
export { default as JobsPage } from './Jobs'
export { default as SupportPage } from './Support'
